repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.1
    hooks:
    - id: check-json5
  - repo: https://github.com/jag-k/pydantic-settings-export
    rev: v1.0.3
    hooks:
      - id: pydantic-settings-export
        entry: pdm run pydantic-settings-export
        language: system
        files: ^src/ot2_rest_node\.py$
