name: ot2
services:
  ot2_module:
    container_name: ot2_module
    image: ghcr.io/ad-sdl/ot2_module
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/ad-sdl/ot2_module:latest
        - ghcr.io/ad-sdl/ot2_module:dev
    command: python ot2_module/src/ot2_rest_node.py --definition definitions/ot2_template.node.yaml
    volumes:
      - ./definitions:/home/madsci/definitions
    network_mode: host
