name: ot2
services:
  ot2_module:
    container_name: ot2_module
    image: ghcr.io/ad-sdl/ot2_module
    env_file:
      - path: .env
        required: false
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/ad-sdl/ot2_module:latest
        - ghcr.io/ad-sdl/ot2_module:dev
    volumes:
      - ./settings.yaml:/home/madsci/settings.yaml
      - ./.madsci:/home/madsci/.madsci
    network_mode: host
