from opentrons import protocol_api


metadata = {
    "protocolName": "Example Name",
    "author": "Kyle khippe@anl.gov",
    "description": "example of reading wells from file",
    "apiLevel": "2.12"
}

def run(protocol: protocol_api.ProtocolContext):

    deck = {}
    pipettes = {}

    ################
    # load labware #
    ################
    deck["1"] = protocol.load_labware("corning_96_wellplate_360ul_flat", "1")
    deck["2"] = protocol.load_labware("corning_96_wellplate_360ul_flat", "2")
    deck["3"] = protocol.load_labware("corning_96_wellplate_360ul_flat", "3")
    deck["4"] = protocol.load_labware("corning_96_wellplate_360ul_flat", "4")
    deck["8"] = protocol.load_labware("opentrons_96_tiprack_1000ul", "8")
    deck["9"] = protocol.load_labware("opentrons_96_tiprack_1000ul", "9")
    pipettes["right"] = protocol.load_instrument("p1000_single_gen2", "right", tip_racks=[deck["8"], deck["9"]])

    ####################
    # execute commands #
    ####################

    # forward primer
    pipettes["right"].pick_up_tip(deck["8"].wells()[0])
    pipettes["right"].aspirate(10, deck["1"]["A1"])
    pipettes["right"].dispense(10, deck["4"]["A1"])
    pipettes["right"].mix(3, 100, deck["4"]["A1"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[1])
    pipettes["right"].aspirate(11, deck["1"]["A2"])
    pipettes["right"].dispense(11, deck["4"]["A2"])
    pipettes["right"].mix(3, 100, deck["4"]["A2"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[2])
    pipettes["right"].aspirate(12, deck["1"]["A3"])
    pipettes["right"].dispense(12, deck["4"]["A3"])
    pipettes["right"].mix(3, 100, deck["4"]["A3"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[3])
    pipettes["right"].aspirate(13, deck["1"]["A4"])
    pipettes["right"].dispense(13, deck["4"]["A4"])
    pipettes["right"].mix(3, 100, deck["4"]["A4"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[4])
    pipettes["right"].aspirate(14, deck["1"]["A5"])
    pipettes["right"].dispense(14, deck["4"]["A5"])
    pipettes["right"].mix(3, 100, deck["4"]["A5"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[5])
    pipettes["right"].aspirate(15, deck["1"]["A6"])
    pipettes["right"].dispense(15, deck["4"]["A6"])
    pipettes["right"].mix(3, 100, deck["4"]["A6"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[6])
    pipettes["right"].aspirate(16, deck["1"]["A7"])
    pipettes["right"].dispense(16, deck["4"]["A7"])
    pipettes["right"].mix(3, 100, deck["4"]["A7"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[7])
    pipettes["right"].aspirate(17, deck["1"]["A8"])
    pipettes["right"].dispense(17, deck["4"]["A8"])
    pipettes["right"].mix(3, 100, deck["4"]["A8"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[8])
    pipettes["right"].aspirate(18, deck["1"]["A9"])
    pipettes["right"].dispense(18, deck["4"]["A9"])
    pipettes["right"].mix(3, 100, deck["4"]["A9"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[9])
    pipettes["right"].aspirate(19, deck["1"]["A10"])
    pipettes["right"].dispense(19, deck["4"]["A10"])
    pipettes["right"].mix(3, 100, deck["4"]["A10"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[10])
    pipettes["right"].aspirate(20, deck["1"]["A11"])
    pipettes["right"].dispense(20, deck["4"]["A11"])
    pipettes["right"].mix(3, 100, deck["4"]["A11"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[11])
    pipettes["right"].aspirate(21, deck["1"]["A12"])
    pipettes["right"].dispense(21, deck["4"]["A12"])
    pipettes["right"].mix(3, 100, deck["4"]["A12"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[12])
    pipettes["right"].aspirate(22, deck["1"]["A13"])
    pipettes["right"].dispense(22, deck["4"]["A13"])
    pipettes["right"].mix(3, 100, deck["4"]["A13"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[13])
    pipettes["right"].aspirate(23, deck["1"]["A14"])
    pipettes["right"].dispense(23, deck["4"]["A14"])
    pipettes["right"].mix(3, 100, deck["4"]["A14"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[14])
    pipettes["right"].aspirate(24, deck["1"]["A15"])
    pipettes["right"].dispense(24, deck["4"]["A15"])
    pipettes["right"].mix(3, 100, deck["4"]["A15"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[15])
    pipettes["right"].aspirate(25, deck["1"]["A16"])
    pipettes["right"].dispense(25, deck["4"]["A16"])
    pipettes["right"].mix(3, 100, deck["4"]["A16"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[16])
    pipettes["right"].aspirate(26, deck["1"]["A17"])
    pipettes["right"].dispense(26, deck["4"]["A17"])
    pipettes["right"].mix(3, 100, deck["4"]["A17"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[17])
    pipettes["right"].aspirate(27, deck["1"]["A18"])
    pipettes["right"].dispense(27, deck["4"]["A18"])
    pipettes["right"].mix(3, 100, deck["4"]["A18"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[18])
    pipettes["right"].aspirate(28, deck["1"]["A19"])
    pipettes["right"].dispense(28, deck["4"]["A19"])
    pipettes["right"].mix(3, 100, deck["4"]["A19"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[19])
    pipettes["right"].aspirate(29, deck["1"]["A20"])
    pipettes["right"].dispense(29, deck["4"]["A20"])
    pipettes["right"].mix(3, 100, deck["4"]["A20"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[20])
    pipettes["right"].aspirate(30, deck["1"]["A21"])
    pipettes["right"].dispense(30, deck["4"]["A21"])
    pipettes["right"].mix(3, 100, deck["4"]["A21"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[21])
    pipettes["right"].aspirate(31, deck["1"]["A22"])
    pipettes["right"].dispense(31, deck["4"]["A22"])
    pipettes["right"].mix(3, 100, deck["4"]["A22"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[22])
    pipettes["right"].aspirate(32, deck["1"]["A23"])
    pipettes["right"].dispense(32, deck["4"]["A23"])
    pipettes["right"].mix(3, 100, deck["4"]["A23"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[23])
    pipettes["right"].aspirate(33, deck["1"]["A24"])
    pipettes["right"].dispense(33, deck["4"]["A24"])
    pipettes["right"].mix(3, 100, deck["4"]["A24"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[24])
    pipettes["right"].aspirate(34, deck["1"]["A25"])
    pipettes["right"].dispense(34, deck["4"]["A25"])
    pipettes["right"].mix(3, 100, deck["4"]["A25"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[25])
    pipettes["right"].aspirate(35, deck["1"]["A26"])
    pipettes["right"].dispense(35, deck["4"]["A26"])
    pipettes["right"].mix(3, 100, deck["4"]["A26"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[26])
    pipettes["right"].aspirate(36, deck["1"]["A27"])
    pipettes["right"].dispense(36, deck["4"]["A27"])
    pipettes["right"].mix(3, 100, deck["4"]["A27"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[27])
    pipettes["right"].aspirate(37, deck["1"]["A28"])
    pipettes["right"].dispense(37, deck["4"]["A28"])
    pipettes["right"].mix(3, 100, deck["4"]["A28"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[28])
    pipettes["right"].aspirate(38, deck["1"]["A29"])
    pipettes["right"].dispense(38, deck["4"]["A29"])
    pipettes["right"].mix(3, 100, deck["4"]["A29"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[29])
    pipettes["right"].aspirate(39, deck["1"]["A30"])
    pipettes["right"].dispense(39, deck["4"]["A30"])
    pipettes["right"].mix(3, 100, deck["4"]["A30"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[30])
    pipettes["right"].aspirate(40, deck["1"]["A31"])
    pipettes["right"].dispense(40, deck["4"]["A31"])
    pipettes["right"].mix(3, 100, deck["4"]["A31"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[31])
    pipettes["right"].aspirate(41, deck["1"]["A32"])
    pipettes["right"].dispense(41, deck["4"]["A32"])
    pipettes["right"].mix(3, 100, deck["4"]["A32"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[32])
    pipettes["right"].aspirate(42, deck["1"]["A33"])
    pipettes["right"].dispense(42, deck["4"]["A33"])
    pipettes["right"].mix(3, 100, deck["4"]["A33"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[33])
    pipettes["right"].aspirate(43, deck["1"]["A34"])
    pipettes["right"].dispense(43, deck["4"]["A34"])
    pipettes["right"].mix(3, 100, deck["4"]["A34"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[34])
    pipettes["right"].aspirate(44, deck["1"]["A35"])
    pipettes["right"].dispense(44, deck["4"]["A35"])
    pipettes["right"].mix(3, 100, deck["4"]["A35"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[35])
    pipettes["right"].aspirate(45, deck["1"]["A36"])
    pipettes["right"].dispense(45, deck["4"]["A36"])
    pipettes["right"].mix(3, 100, deck["4"]["A36"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[36])
    pipettes["right"].aspirate(46, deck["1"]["A37"])
    pipettes["right"].dispense(46, deck["4"]["A37"])
    pipettes["right"].mix(3, 100, deck["4"]["A37"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[37])
    pipettes["right"].aspirate(47, deck["1"]["A38"])
    pipettes["right"].dispense(47, deck["4"]["A38"])
    pipettes["right"].mix(3, 100, deck["4"]["A38"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[38])
    pipettes["right"].aspirate(48, deck["1"]["A39"])
    pipettes["right"].dispense(48, deck["4"]["A39"])
    pipettes["right"].mix(3, 100, deck["4"]["A39"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[39])
    pipettes["right"].aspirate(49, deck["1"]["A40"])
    pipettes["right"].dispense(49, deck["4"]["A40"])
    pipettes["right"].mix(3, 100, deck["4"]["A40"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[40])
    pipettes["right"].aspirate(50, deck["1"]["A41"])
    pipettes["right"].dispense(50, deck["4"]["A41"])
    pipettes["right"].mix(3, 100, deck["4"]["A41"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[41])
    pipettes["right"].aspirate(51, deck["1"]["A42"])
    pipettes["right"].dispense(51, deck["4"]["A42"])
    pipettes["right"].mix(3, 100, deck["4"]["A42"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[42])
    pipettes["right"].aspirate(52, deck["1"]["A43"])
    pipettes["right"].dispense(52, deck["4"]["A43"])
    pipettes["right"].mix(3, 100, deck["4"]["A43"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[43])
    pipettes["right"].aspirate(53, deck["1"]["A44"])
    pipettes["right"].dispense(53, deck["4"]["A44"])
    pipettes["right"].mix(3, 100, deck["4"]["A44"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[44])
    pipettes["right"].aspirate(54, deck["1"]["A45"])
    pipettes["right"].dispense(54, deck["4"]["A45"])
    pipettes["right"].mix(3, 100, deck["4"]["A45"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[45])
    pipettes["right"].aspirate(55, deck["1"]["A46"])
    pipettes["right"].dispense(55, deck["4"]["A46"])
    pipettes["right"].mix(3, 100, deck["4"]["A46"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[46])
    pipettes["right"].aspirate(56, deck["1"]["A47"])
    pipettes["right"].dispense(56, deck["4"]["A47"])
    pipettes["right"].mix(3, 100, deck["4"]["A47"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[47])
    pipettes["right"].aspirate(57, deck["1"]["A48"])
    pipettes["right"].dispense(57, deck["4"]["A48"])
    pipettes["right"].mix(3, 100, deck["4"]["A48"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[48])
    pipettes["right"].aspirate(58, deck["1"]["A49"])
    pipettes["right"].dispense(58, deck["4"]["A49"])
    pipettes["right"].mix(3, 100, deck["4"]["A49"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[49])
    pipettes["right"].aspirate(59, deck["1"]["A50"])
    pipettes["right"].dispense(59, deck["4"]["A50"])
    pipettes["right"].mix(3, 100, deck["4"]["A50"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[50])
    pipettes["right"].aspirate(60, deck["1"]["A51"])
    pipettes["right"].dispense(60, deck["4"]["A51"])
    pipettes["right"].mix(3, 100, deck["4"]["A51"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[51])
    pipettes["right"].aspirate(61, deck["1"]["A52"])
    pipettes["right"].dispense(61, deck["4"]["A52"])
    pipettes["right"].mix(3, 100, deck["4"]["A52"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[52])
    pipettes["right"].aspirate(62, deck["1"]["A53"])
    pipettes["right"].dispense(62, deck["4"]["A53"])
    pipettes["right"].mix(3, 100, deck["4"]["A53"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[53])
    pipettes["right"].aspirate(63, deck["1"]["A54"])
    pipettes["right"].dispense(63, deck["4"]["A54"])
    pipettes["right"].mix(3, 100, deck["4"]["A54"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[54])
    pipettes["right"].aspirate(64, deck["1"]["A55"])
    pipettes["right"].dispense(64, deck["4"]["A55"])
    pipettes["right"].mix(3, 100, deck["4"]["A55"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[55])
    pipettes["right"].aspirate(65, deck["1"]["A56"])
    pipettes["right"].dispense(65, deck["4"]["A56"])
    pipettes["right"].mix(3, 100, deck["4"]["A56"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[56])
    pipettes["right"].aspirate(66, deck["1"]["A57"])
    pipettes["right"].dispense(66, deck["4"]["A57"])
    pipettes["right"].mix(3, 100, deck["4"]["A57"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[57])
    pipettes["right"].aspirate(67, deck["1"]["A58"])
    pipettes["right"].dispense(67, deck["4"]["A58"])
    pipettes["right"].mix(3, 100, deck["4"]["A58"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[58])
    pipettes["right"].aspirate(68, deck["1"]["A59"])
    pipettes["right"].dispense(68, deck["4"]["A59"])
    pipettes["right"].mix(3, 100, deck["4"]["A59"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[59])
    pipettes["right"].aspirate(69, deck["1"]["A60"])
    pipettes["right"].dispense(69, deck["4"]["A60"])
    pipettes["right"].mix(3, 100, deck["4"]["A60"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[60])
    pipettes["right"].aspirate(70, deck["1"]["A61"])
    pipettes["right"].dispense(70, deck["4"]["A61"])
    pipettes["right"].mix(3, 100, deck["4"]["A61"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[61])
    pipettes["right"].aspirate(71, deck["1"]["A62"])
    pipettes["right"].dispense(71, deck["4"]["A62"])
    pipettes["right"].mix(3, 100, deck["4"]["A62"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[62])
    pipettes["right"].aspirate(72, deck["1"]["A63"])
    pipettes["right"].dispense(72, deck["4"]["A63"])
    pipettes["right"].mix(3, 100, deck["4"]["A63"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[63])
    pipettes["right"].aspirate(73, deck["1"]["A64"])
    pipettes["right"].dispense(73, deck["4"]["A64"])
    pipettes["right"].mix(3, 100, deck["4"]["A64"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[64])
    pipettes["right"].aspirate(74, deck["1"]["A65"])
    pipettes["right"].dispense(74, deck["4"]["A65"])
    pipettes["right"].mix(3, 100, deck["4"]["A65"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[65])
    pipettes["right"].aspirate(75, deck["1"]["A66"])
    pipettes["right"].dispense(75, deck["4"]["A66"])
    pipettes["right"].mix(3, 100, deck["4"]["A66"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[66])
    pipettes["right"].aspirate(76, deck["1"]["A67"])
    pipettes["right"].dispense(76, deck["4"]["A67"])
    pipettes["right"].mix(3, 100, deck["4"]["A67"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[67])
    pipettes["right"].aspirate(77, deck["1"]["A68"])
    pipettes["right"].dispense(77, deck["4"]["A68"])
    pipettes["right"].mix(3, 100, deck["4"]["A68"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[68])
    pipettes["right"].aspirate(78, deck["1"]["A69"])
    pipettes["right"].dispense(78, deck["4"]["A69"])
    pipettes["right"].mix(3, 100, deck["4"]["A69"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[69])
    pipettes["right"].aspirate(79, deck["1"]["A70"])
    pipettes["right"].dispense(79, deck["4"]["A70"])
    pipettes["right"].mix(3, 100, deck["4"]["A70"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[70])
    pipettes["right"].aspirate(80, deck["1"]["A71"])
    pipettes["right"].dispense(80, deck["4"]["A71"])
    pipettes["right"].mix(3, 100, deck["4"]["A71"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[71])
    pipettes["right"].aspirate(81, deck["1"]["A72"])
    pipettes["right"].dispense(81, deck["4"]["A72"])
    pipettes["right"].mix(3, 100, deck["4"]["A72"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[72])
    pipettes["right"].aspirate(82, deck["1"]["A73"])
    pipettes["right"].dispense(82, deck["4"]["A73"])
    pipettes["right"].mix(3, 100, deck["4"]["A73"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[73])
    pipettes["right"].aspirate(83, deck["1"]["A74"])
    pipettes["right"].dispense(83, deck["4"]["A74"])
    pipettes["right"].mix(3, 100, deck["4"]["A74"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[74])
    pipettes["right"].aspirate(84, deck["1"]["A75"])
    pipettes["right"].dispense(84, deck["4"]["A75"])
    pipettes["right"].mix(3, 100, deck["4"]["A75"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[75])
    pipettes["right"].aspirate(85, deck["1"]["A76"])
    pipettes["right"].dispense(85, deck["4"]["A76"])
    pipettes["right"].mix(3, 100, deck["4"]["A76"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[76])
    pipettes["right"].aspirate(86, deck["1"]["A77"])
    pipettes["right"].dispense(86, deck["4"]["A77"])
    pipettes["right"].mix(3, 100, deck["4"]["A77"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[77])
    pipettes["right"].aspirate(87, deck["1"]["A78"])
    pipettes["right"].dispense(87, deck["4"]["A78"])
    pipettes["right"].mix(3, 100, deck["4"]["A78"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[78])
    pipettes["right"].aspirate(88, deck["1"]["A79"])
    pipettes["right"].dispense(88, deck["4"]["A79"])
    pipettes["right"].mix(3, 100, deck["4"]["A79"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[79])
    pipettes["right"].aspirate(89, deck["1"]["A80"])
    pipettes["right"].dispense(89, deck["4"]["A80"])
    pipettes["right"].mix(3, 100, deck["4"]["A80"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[80])
    pipettes["right"].aspirate(90, deck["1"]["A81"])
    pipettes["right"].dispense(90, deck["4"]["A81"])
    pipettes["right"].mix(3, 100, deck["4"]["A81"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[81])
    pipettes["right"].aspirate(91, deck["1"]["A82"])
    pipettes["right"].dispense(91, deck["4"]["A82"])
    pipettes["right"].mix(3, 100, deck["4"]["A82"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[82])
    pipettes["right"].aspirate(92, deck["1"]["A83"])
    pipettes["right"].dispense(92, deck["4"]["A83"])
    pipettes["right"].mix(3, 100, deck["4"]["A83"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[83])
    pipettes["right"].aspirate(93, deck["1"]["A84"])
    pipettes["right"].dispense(93, deck["4"]["A84"])
    pipettes["right"].mix(3, 100, deck["4"]["A84"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[84])
    pipettes["right"].aspirate(94, deck["1"]["A85"])
    pipettes["right"].dispense(94, deck["4"]["A85"])
    pipettes["right"].mix(3, 100, deck["4"]["A85"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[85])
    pipettes["right"].aspirate(95, deck["1"]["A86"])
    pipettes["right"].dispense(95, deck["4"]["A86"])
    pipettes["right"].mix(3, 100, deck["4"]["A86"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[86])
    pipettes["right"].aspirate(96, deck["1"]["A87"])
    pipettes["right"].dispense(96, deck["4"]["A87"])
    pipettes["right"].mix(3, 100, deck["4"]["A87"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[87])
    pipettes["right"].aspirate(97, deck["1"]["A88"])
    pipettes["right"].dispense(97, deck["4"]["A88"])
    pipettes["right"].mix(3, 100, deck["4"]["A88"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[88])
    pipettes["right"].aspirate(98, deck["1"]["A89"])
    pipettes["right"].dispense(98, deck["4"]["A89"])
    pipettes["right"].mix(3, 100, deck["4"]["A89"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[89])
    pipettes["right"].aspirate(99, deck["1"]["A90"])
    pipettes["right"].dispense(99, deck["4"]["A90"])
    pipettes["right"].mix(3, 100, deck["4"]["A90"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[90])
    pipettes["right"].aspirate(100, deck["1"]["A91"])
    pipettes["right"].dispense(100, deck["4"]["A91"])
    pipettes["right"].mix(3, 100, deck["4"]["A91"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[91])
    pipettes["right"].aspirate(101, deck["1"]["A92"])
    pipettes["right"].dispense(101, deck["4"]["A92"])
    pipettes["right"].mix(3, 100, deck["4"]["A92"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[92])
    pipettes["right"].aspirate(102, deck["1"]["A93"])
    pipettes["right"].dispense(102, deck["4"]["A93"])
    pipettes["right"].mix(3, 100, deck["4"]["A93"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[93])
    pipettes["right"].aspirate(103, deck["1"]["A94"])
    pipettes["right"].dispense(103, deck["4"]["A94"])
    pipettes["right"].mix(3, 100, deck["4"]["A94"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["8"].wells()[94])
    pipettes["right"].aspirate(104, deck["1"]["A95"])
    pipettes["right"].dispense(104, deck["4"]["A95"])
    pipettes["right"].mix(3, 100, deck["4"]["A95"])
    pipettes["right"].drop_tip()


    # backward primer
    pipettes["right"].pick_up_tip(deck["8"].wells()[95])
    pipettes["right"].aspirate(10, deck["2"]["A95"])
    pipettes["right"].dispense(10, deck["4"]["A95"])
    pipettes["right"].mix(3, 100, deck["4"]["A95"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[0])
    pipettes["right"].aspirate(11, deck["2"]["A94"])
    pipettes["right"].dispense(11, deck["4"]["A94"])
    pipettes["right"].mix(3, 100, deck["4"]["A94"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[1])
    pipettes["right"].aspirate(12, deck["2"]["A93"])
    pipettes["right"].dispense(12, deck["4"]["A93"])
    pipettes["right"].mix(3, 100, deck["4"]["A93"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[2])
    pipettes["right"].aspirate(13, deck["2"]["A92"])
    pipettes["right"].dispense(13, deck["4"]["A92"])
    pipettes["right"].mix(3, 100, deck["4"]["A92"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[3])
    pipettes["right"].aspirate(14, deck["2"]["A91"])
    pipettes["right"].dispense(14, deck["4"]["A91"])
    pipettes["right"].mix(3, 100, deck["4"]["A91"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[4])
    pipettes["right"].aspirate(15, deck["2"]["A90"])
    pipettes["right"].dispense(15, deck["4"]["A90"])
    pipettes["right"].mix(3, 100, deck["4"]["A90"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[5])
    pipettes["right"].aspirate(16, deck["2"]["A89"])
    pipettes["right"].dispense(16, deck["4"]["A89"])
    pipettes["right"].mix(3, 100, deck["4"]["A89"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[6])
    pipettes["right"].aspirate(17, deck["2"]["A88"])
    pipettes["right"].dispense(17, deck["4"]["A88"])
    pipettes["right"].mix(3, 100, deck["4"]["A88"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[7])
    pipettes["right"].aspirate(18, deck["2"]["A87"])
    pipettes["right"].dispense(18, deck["4"]["A87"])
    pipettes["right"].mix(3, 100, deck["4"]["A87"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[8])
    pipettes["right"].aspirate(19, deck["2"]["A86"])
    pipettes["right"].dispense(19, deck["4"]["A86"])
    pipettes["right"].mix(3, 100, deck["4"]["A86"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[9])
    pipettes["right"].aspirate(20, deck["2"]["A85"])
    pipettes["right"].dispense(20, deck["4"]["A85"])
    pipettes["right"].mix(3, 100, deck["4"]["A85"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[10])
    pipettes["right"].aspirate(21, deck["2"]["A84"])
    pipettes["right"].dispense(21, deck["4"]["A84"])
    pipettes["right"].mix(3, 100, deck["4"]["A84"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[11])
    pipettes["right"].aspirate(22, deck["2"]["A83"])
    pipettes["right"].dispense(22, deck["4"]["A83"])
    pipettes["right"].mix(3, 100, deck["4"]["A83"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[12])
    pipettes["right"].aspirate(23, deck["2"]["A82"])
    pipettes["right"].dispense(23, deck["4"]["A82"])
    pipettes["right"].mix(3, 100, deck["4"]["A82"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[13])
    pipettes["right"].aspirate(24, deck["2"]["A81"])
    pipettes["right"].dispense(24, deck["4"]["A81"])
    pipettes["right"].mix(3, 100, deck["4"]["A81"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[14])
    pipettes["right"].aspirate(25, deck["2"]["A80"])
    pipettes["right"].dispense(25, deck["4"]["A80"])
    pipettes["right"].mix(3, 100, deck["4"]["A80"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[15])
    pipettes["right"].aspirate(26, deck["2"]["A79"])
    pipettes["right"].dispense(26, deck["4"]["A79"])
    pipettes["right"].mix(3, 100, deck["4"]["A79"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[16])
    pipettes["right"].aspirate(27, deck["2"]["A78"])
    pipettes["right"].dispense(27, deck["4"]["A78"])
    pipettes["right"].mix(3, 100, deck["4"]["A78"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[17])
    pipettes["right"].aspirate(28, deck["2"]["A77"])
    pipettes["right"].dispense(28, deck["4"]["A77"])
    pipettes["right"].mix(3, 100, deck["4"]["A77"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[18])
    pipettes["right"].aspirate(29, deck["2"]["A76"])
    pipettes["right"].dispense(29, deck["4"]["A76"])
    pipettes["right"].mix(3, 100, deck["4"]["A76"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[19])
    pipettes["right"].aspirate(30, deck["2"]["A75"])
    pipettes["right"].dispense(30, deck["4"]["A75"])
    pipettes["right"].mix(3, 100, deck["4"]["A75"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[20])
    pipettes["right"].aspirate(31, deck["2"]["A74"])
    pipettes["right"].dispense(31, deck["4"]["A74"])
    pipettes["right"].mix(3, 100, deck["4"]["A74"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[21])
    pipettes["right"].aspirate(32, deck["2"]["A73"])
    pipettes["right"].dispense(32, deck["4"]["A73"])
    pipettes["right"].mix(3, 100, deck["4"]["A73"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[22])
    pipettes["right"].aspirate(33, deck["2"]["A72"])
    pipettes["right"].dispense(33, deck["4"]["A72"])
    pipettes["right"].mix(3, 100, deck["4"]["A72"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[23])
    pipettes["right"].aspirate(34, deck["2"]["A71"])
    pipettes["right"].dispense(34, deck["4"]["A71"])
    pipettes["right"].mix(3, 100, deck["4"]["A71"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[24])
    pipettes["right"].aspirate(35, deck["2"]["A70"])
    pipettes["right"].dispense(35, deck["4"]["A70"])
    pipettes["right"].mix(3, 100, deck["4"]["A70"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[25])
    pipettes["right"].aspirate(36, deck["2"]["A69"])
    pipettes["right"].dispense(36, deck["4"]["A69"])
    pipettes["right"].mix(3, 100, deck["4"]["A69"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[26])
    pipettes["right"].aspirate(37, deck["2"]["A68"])
    pipettes["right"].dispense(37, deck["4"]["A68"])
    pipettes["right"].mix(3, 100, deck["4"]["A68"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[27])
    pipettes["right"].aspirate(38, deck["2"]["A67"])
    pipettes["right"].dispense(38, deck["4"]["A67"])
    pipettes["right"].mix(3, 100, deck["4"]["A67"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[28])
    pipettes["right"].aspirate(39, deck["2"]["A66"])
    pipettes["right"].dispense(39, deck["4"]["A66"])
    pipettes["right"].mix(3, 100, deck["4"]["A66"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[29])
    pipettes["right"].aspirate(40, deck["2"]["A65"])
    pipettes["right"].dispense(40, deck["4"]["A65"])
    pipettes["right"].mix(3, 100, deck["4"]["A65"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[30])
    pipettes["right"].aspirate(41, deck["2"]["A64"])
    pipettes["right"].dispense(41, deck["4"]["A64"])
    pipettes["right"].mix(3, 100, deck["4"]["A64"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[31])
    pipettes["right"].aspirate(42, deck["2"]["A63"])
    pipettes["right"].dispense(42, deck["4"]["A63"])
    pipettes["right"].mix(3, 100, deck["4"]["A63"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[32])
    pipettes["right"].aspirate(43, deck["2"]["A62"])
    pipettes["right"].dispense(43, deck["4"]["A62"])
    pipettes["right"].mix(3, 100, deck["4"]["A62"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[33])
    pipettes["right"].aspirate(44, deck["2"]["A61"])
    pipettes["right"].dispense(44, deck["4"]["A61"])
    pipettes["right"].mix(3, 100, deck["4"]["A61"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[34])
    pipettes["right"].aspirate(45, deck["2"]["A60"])
    pipettes["right"].dispense(45, deck["4"]["A60"])
    pipettes["right"].mix(3, 100, deck["4"]["A60"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[35])
    pipettes["right"].aspirate(46, deck["2"]["A59"])
    pipettes["right"].dispense(46, deck["4"]["A59"])
    pipettes["right"].mix(3, 100, deck["4"]["A59"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[36])
    pipettes["right"].aspirate(47, deck["2"]["A58"])
    pipettes["right"].dispense(47, deck["4"]["A58"])
    pipettes["right"].mix(3, 100, deck["4"]["A58"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[37])
    pipettes["right"].aspirate(48, deck["2"]["A57"])
    pipettes["right"].dispense(48, deck["4"]["A57"])
    pipettes["right"].mix(3, 100, deck["4"]["A57"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[38])
    pipettes["right"].aspirate(49, deck["2"]["A56"])
    pipettes["right"].dispense(49, deck["4"]["A56"])
    pipettes["right"].mix(3, 100, deck["4"]["A56"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[39])
    pipettes["right"].aspirate(50, deck["2"]["A55"])
    pipettes["right"].dispense(50, deck["4"]["A55"])
    pipettes["right"].mix(3, 100, deck["4"]["A55"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[40])
    pipettes["right"].aspirate(51, deck["2"]["A54"])
    pipettes["right"].dispense(51, deck["4"]["A54"])
    pipettes["right"].mix(3, 100, deck["4"]["A54"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[41])
    pipettes["right"].aspirate(52, deck["2"]["A53"])
    pipettes["right"].dispense(52, deck["4"]["A53"])
    pipettes["right"].mix(3, 100, deck["4"]["A53"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[42])
    pipettes["right"].aspirate(53, deck["2"]["A52"])
    pipettes["right"].dispense(53, deck["4"]["A52"])
    pipettes["right"].mix(3, 100, deck["4"]["A52"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[43])
    pipettes["right"].aspirate(54, deck["2"]["A51"])
    pipettes["right"].dispense(54, deck["4"]["A51"])
    pipettes["right"].mix(3, 100, deck["4"]["A51"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[44])
    pipettes["right"].aspirate(55, deck["2"]["A50"])
    pipettes["right"].dispense(55, deck["4"]["A50"])
    pipettes["right"].mix(3, 100, deck["4"]["A50"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[45])
    pipettes["right"].aspirate(56, deck["2"]["A49"])
    pipettes["right"].dispense(56, deck["4"]["A49"])
    pipettes["right"].mix(3, 100, deck["4"]["A49"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[46])
    pipettes["right"].aspirate(57, deck["2"]["A48"])
    pipettes["right"].dispense(57, deck["4"]["A48"])
    pipettes["right"].mix(3, 100, deck["4"]["A48"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[47])
    pipettes["right"].aspirate(58, deck["2"]["A47"])
    pipettes["right"].dispense(58, deck["4"]["A47"])
    pipettes["right"].mix(3, 100, deck["4"]["A47"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[48])
    pipettes["right"].aspirate(59, deck["2"]["A46"])
    pipettes["right"].dispense(59, deck["4"]["A46"])
    pipettes["right"].mix(3, 100, deck["4"]["A46"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[49])
    pipettes["right"].aspirate(60, deck["2"]["A45"])
    pipettes["right"].dispense(60, deck["4"]["A45"])
    pipettes["right"].mix(3, 100, deck["4"]["A45"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[50])
    pipettes["right"].aspirate(61, deck["2"]["A44"])
    pipettes["right"].dispense(61, deck["4"]["A44"])
    pipettes["right"].mix(3, 100, deck["4"]["A44"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[51])
    pipettes["right"].aspirate(62, deck["2"]["A43"])
    pipettes["right"].dispense(62, deck["4"]["A43"])
    pipettes["right"].mix(3, 100, deck["4"]["A43"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[52])
    pipettes["right"].aspirate(63, deck["2"]["A42"])
    pipettes["right"].dispense(63, deck["4"]["A42"])
    pipettes["right"].mix(3, 100, deck["4"]["A42"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[53])
    pipettes["right"].aspirate(64, deck["2"]["A41"])
    pipettes["right"].dispense(64, deck["4"]["A41"])
    pipettes["right"].mix(3, 100, deck["4"]["A41"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[54])
    pipettes["right"].aspirate(65, deck["2"]["A40"])
    pipettes["right"].dispense(65, deck["4"]["A40"])
    pipettes["right"].mix(3, 100, deck["4"]["A40"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[55])
    pipettes["right"].aspirate(66, deck["2"]["A39"])
    pipettes["right"].dispense(66, deck["4"]["A39"])
    pipettes["right"].mix(3, 100, deck["4"]["A39"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[56])
    pipettes["right"].aspirate(67, deck["2"]["A38"])
    pipettes["right"].dispense(67, deck["4"]["A38"])
    pipettes["right"].mix(3, 100, deck["4"]["A38"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[57])
    pipettes["right"].aspirate(68, deck["2"]["A37"])
    pipettes["right"].dispense(68, deck["4"]["A37"])
    pipettes["right"].mix(3, 100, deck["4"]["A37"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[58])
    pipettes["right"].aspirate(69, deck["2"]["A36"])
    pipettes["right"].dispense(69, deck["4"]["A36"])
    pipettes["right"].mix(3, 100, deck["4"]["A36"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[59])
    pipettes["right"].aspirate(70, deck["2"]["A35"])
    pipettes["right"].dispense(70, deck["4"]["A35"])
    pipettes["right"].mix(3, 100, deck["4"]["A35"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[60])
    pipettes["right"].aspirate(71, deck["2"]["A34"])
    pipettes["right"].dispense(71, deck["4"]["A34"])
    pipettes["right"].mix(3, 100, deck["4"]["A34"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[61])
    pipettes["right"].aspirate(72, deck["2"]["A33"])
    pipettes["right"].dispense(72, deck["4"]["A33"])
    pipettes["right"].mix(3, 100, deck["4"]["A33"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[62])
    pipettes["right"].aspirate(73, deck["2"]["A32"])
    pipettes["right"].dispense(73, deck["4"]["A32"])
    pipettes["right"].mix(3, 100, deck["4"]["A32"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[63])
    pipettes["right"].aspirate(74, deck["2"]["A31"])
    pipettes["right"].dispense(74, deck["4"]["A31"])
    pipettes["right"].mix(3, 100, deck["4"]["A31"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[64])
    pipettes["right"].aspirate(75, deck["2"]["A30"])
    pipettes["right"].dispense(75, deck["4"]["A30"])
    pipettes["right"].mix(3, 100, deck["4"]["A30"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[65])
    pipettes["right"].aspirate(76, deck["2"]["A29"])
    pipettes["right"].dispense(76, deck["4"]["A29"])
    pipettes["right"].mix(3, 100, deck["4"]["A29"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[66])
    pipettes["right"].aspirate(77, deck["2"]["A28"])
    pipettes["right"].dispense(77, deck["4"]["A28"])
    pipettes["right"].mix(3, 100, deck["4"]["A28"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[67])
    pipettes["right"].aspirate(78, deck["2"]["A27"])
    pipettes["right"].dispense(78, deck["4"]["A27"])
    pipettes["right"].mix(3, 100, deck["4"]["A27"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[68])
    pipettes["right"].aspirate(79, deck["2"]["A26"])
    pipettes["right"].dispense(79, deck["4"]["A26"])
    pipettes["right"].mix(3, 100, deck["4"]["A26"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[69])
    pipettes["right"].aspirate(80, deck["2"]["A25"])
    pipettes["right"].dispense(80, deck["4"]["A25"])
    pipettes["right"].mix(3, 100, deck["4"]["A25"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[70])
    pipettes["right"].aspirate(81, deck["2"]["A24"])
    pipettes["right"].dispense(81, deck["4"]["A24"])
    pipettes["right"].mix(3, 100, deck["4"]["A24"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[71])
    pipettes["right"].aspirate(82, deck["2"]["A23"])
    pipettes["right"].dispense(82, deck["4"]["A23"])
    pipettes["right"].mix(3, 100, deck["4"]["A23"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[72])
    pipettes["right"].aspirate(83, deck["2"]["A22"])
    pipettes["right"].dispense(83, deck["4"]["A22"])
    pipettes["right"].mix(3, 100, deck["4"]["A22"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[73])
    pipettes["right"].aspirate(84, deck["2"]["A21"])
    pipettes["right"].dispense(84, deck["4"]["A21"])
    pipettes["right"].mix(3, 100, deck["4"]["A21"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[74])
    pipettes["right"].aspirate(85, deck["2"]["A20"])
    pipettes["right"].dispense(85, deck["4"]["A20"])
    pipettes["right"].mix(3, 100, deck["4"]["A20"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[75])
    pipettes["right"].aspirate(86, deck["2"]["A19"])
    pipettes["right"].dispense(86, deck["4"]["A19"])
    pipettes["right"].mix(3, 100, deck["4"]["A19"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[76])
    pipettes["right"].aspirate(87, deck["2"]["A18"])
    pipettes["right"].dispense(87, deck["4"]["A18"])
    pipettes["right"].mix(3, 100, deck["4"]["A18"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[77])
    pipettes["right"].aspirate(88, deck["2"]["A17"])
    pipettes["right"].dispense(88, deck["4"]["A17"])
    pipettes["right"].mix(3, 100, deck["4"]["A17"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[78])
    pipettes["right"].aspirate(89, deck["2"]["A16"])
    pipettes["right"].dispense(89, deck["4"]["A16"])
    pipettes["right"].mix(3, 100, deck["4"]["A16"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[79])
    pipettes["right"].aspirate(90, deck["2"]["A15"])
    pipettes["right"].dispense(90, deck["4"]["A15"])
    pipettes["right"].mix(3, 100, deck["4"]["A15"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[80])
    pipettes["right"].aspirate(91, deck["2"]["A14"])
    pipettes["right"].dispense(91, deck["4"]["A14"])
    pipettes["right"].mix(3, 100, deck["4"]["A14"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[81])
    pipettes["right"].aspirate(92, deck["2"]["A13"])
    pipettes["right"].dispense(92, deck["4"]["A13"])
    pipettes["right"].mix(3, 100, deck["4"]["A13"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[82])
    pipettes["right"].aspirate(93, deck["2"]["A12"])
    pipettes["right"].dispense(93, deck["4"]["A12"])
    pipettes["right"].mix(3, 100, deck["4"]["A12"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[83])
    pipettes["right"].aspirate(94, deck["2"]["A11"])
    pipettes["right"].dispense(94, deck["4"]["A11"])
    pipettes["right"].mix(3, 100, deck["4"]["A11"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[84])
    pipettes["right"].aspirate(95, deck["2"]["A10"])
    pipettes["right"].dispense(95, deck["4"]["A10"])
    pipettes["right"].mix(3, 100, deck["4"]["A10"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[85])
    pipettes["right"].aspirate(96, deck["2"]["A9"])
    pipettes["right"].dispense(96, deck["4"]["A9"])
    pipettes["right"].mix(3, 100, deck["4"]["A9"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[86])
    pipettes["right"].aspirate(97, deck["2"]["A8"])
    pipettes["right"].dispense(97, deck["4"]["A8"])
    pipettes["right"].mix(3, 100, deck["4"]["A8"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[87])
    pipettes["right"].aspirate(98, deck["2"]["A7"])
    pipettes["right"].dispense(98, deck["4"]["A7"])
    pipettes["right"].mix(3, 100, deck["4"]["A7"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[88])
    pipettes["right"].aspirate(99, deck["2"]["A6"])
    pipettes["right"].dispense(99, deck["4"]["A6"])
    pipettes["right"].mix(3, 100, deck["4"]["A6"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[89])
    pipettes["right"].aspirate(100, deck["2"]["A5"])
    pipettes["right"].dispense(100, deck["4"]["A5"])
    pipettes["right"].mix(3, 100, deck["4"]["A5"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[90])
    pipettes["right"].aspirate(101, deck["2"]["A4"])
    pipettes["right"].dispense(101, deck["4"]["A4"])
    pipettes["right"].mix(3, 100, deck["4"]["A4"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[91])
    pipettes["right"].aspirate(102, deck["2"]["A3"])
    pipettes["right"].dispense(102, deck["4"]["A3"])
    pipettes["right"].mix(3, 100, deck["4"]["A3"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[92])
    pipettes["right"].aspirate(103, deck["2"]["A2"])
    pipettes["right"].dispense(103, deck["4"]["A2"])
    pipettes["right"].mix(3, 100, deck["4"]["A2"])
    pipettes["right"].drop_tip()

    pipettes["right"].pick_up_tip(deck["9"].wells()[93])
    pipettes["right"].aspirate(104, deck["2"]["A1"])
    pipettes["right"].dispense(104, deck["4"]["A1"])
    pipettes["right"].mix(3, 100, deck["4"]["A1"])
    pipettes["right"].drop_tip()
