name: Pre-Commit Checks

on:
  push: # Run for every push
    branches: ["*"]
    tags: ["*"]
  workflow_dispatch: # Run manually

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout code
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      env:
        PDM_USE_UV: "True"
      run: pdm install
    - uses: pre-commit/action@v3.0.1
      name: Run Pre-Commit Checks
